Tom branch
lorilew/python-101 pull request #1
Opened 2019-09-06 10:18 UTC by Tom-Fynes

2019-09-18 13:21 UTC, lorilew commented on homework/grade2/Tom-grade-2.py
> +# homework for grade 2
I have the feeling you really like the `input` method!

2019-09-18 13:23 UTC, lorilew commented on homework/grade2/Tom-grade-2.py
> +def doathing(number):
Not taught you this yet, but in python3 it's good practice to follow pep8 coding standards. So function names use underscores, eg: `do_a_thing` and class names are Camel case, eg ClassThatDoesStuff.

2019-09-18 13:26 UTC, lorilew requested changes

2019-09-18 13:26 UTC, lorilew commented on homework/grade2/Tom-grade-2.py
> +def lastthing(somestring):
For good practice can you add pydocs (Grade 3) to this? It will make it easier to understand.

2019-09-18 13:28 UTC, lorilew commented on homework/grade2/Tom-grade-2.py
> +def lastthing(somestring):
https://realpython.com/documenting-python-code/

2020-06-09 07:44 UTC, Tom-Fynes commented
Forgot this was even still open haha, closing this off as no more python training :slightly_frowning_face: :stuck_out_tongue:

2020-06-09 07:44 UTC, closed without merging